kind: Deployment
apiVersion: apps/v1
metadata:
  name: pakayatechnologies
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pakayatechnologies
  template:
    metadata:
      labels:
        app: pakayatechnologies
    spec:
      containers:
        - name: pakayatechnologies
          image: bmsowoya/pakayatechnologies.co.za
          ports:
            - containerPort: 80
